//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_r/code/input/InputAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputAsset : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAsset"",
    ""maps"": [
        {
            ""name"": ""Web"",
            ""id"": ""6da2bf5b-221d-4323-9ba8-ec3a3aa302e0"",
            ""actions"": [
                {
                    ""name"": ""NumberOne"",
                    ""type"": ""Button"",
                    ""id"": ""cadcfec7-88c3-4080-a9fb-a844e8943074"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberTwo"",
                    ""type"": ""Button"",
                    ""id"": ""01397eb7-d6d5-4e0d-9129-794c0510dae4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberThree"",
                    ""type"": ""Button"",
                    ""id"": ""24a87e45-b54e-46b4-acc9-79f2a459a9fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberFour"",
                    ""type"": ""Button"",
                    ""id"": ""a6b1fc38-f267-4f61-9fce-b9e1fe719f2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberFive"",
                    ""type"": ""Button"",
                    ""id"": ""372183b1-c73a-462a-a059-f839a4c787d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberSix"",
                    ""type"": ""Button"",
                    ""id"": ""879e93e1-e776-490f-a5ff-ada1d740b557"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberSeven"",
                    ""type"": ""Button"",
                    ""id"": ""c853a857-58aa-4658-b252-31ee4e599eca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberEight"",
                    ""type"": ""Button"",
                    ""id"": ""3bab2869-1158-43ec-b9ad-c76c7de6078f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberNine"",
                    ""type"": ""Button"",
                    ""id"": ""f9edae3b-4048-412e-ba90-71cf96f99c05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NumberZero"",
                    ""type"": ""Button"",
                    ""id"": ""0f8f7f8a-90e5-4ab3-92ac-4aaf7ae83fd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""0653153c-69ac-4994-85b1-c166f7cab28d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clear"",
                    ""type"": ""Button"",
                    ""id"": ""27382dbb-83b5-4817-b289-878a208b153a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""58f884d0-7672-41a0-aee2-e7e89e623430"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NegativeSign"",
                    ""type"": ""Button"",
                    ""id"": ""95912087-be56-489f-9c5a-8ee1d5fcfdd6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d9a282fa-ab68-47fc-9151-33f557fcdd8b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bffc88bf-276e-4ea4-a33c-b4621872d5ce"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b8544cd-12a2-4c05-8fae-79b1b1b4be95"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53e2cfa6-62df-442a-bbbd-abfeeb999da2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7690a8ab-426f-4bf1-8053-d7918d1f7843"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberFive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""871cdc05-f66a-407f-adf8-657d16260527"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberSix"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ec0c065-739d-47b3-8311-eac230facd39"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberSeven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffae451a-047f-4659-97fa-50cadfeed938"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberEight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8270690-98c5-4f91-afaf-2d9d64881e78"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberNine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a09525d-375f-4d6c-ac82-dc81753854f5"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NumberZero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f95393b1-bd8c-497f-8cb0-9ba5cfc06317"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19d71ae0-65de-4de9-b635-8dfb9cf06938"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""506b4e1e-fd12-4808-9196-7e8bbbd03660"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c4e5636-ce4b-4eac-8ba2-3f11ca52f15e"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NegativeSign"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Web
        m_Web = asset.FindActionMap("Web", throwIfNotFound: true);
        m_Web_NumberOne = m_Web.FindAction("NumberOne", throwIfNotFound: true);
        m_Web_NumberTwo = m_Web.FindAction("NumberTwo", throwIfNotFound: true);
        m_Web_NumberThree = m_Web.FindAction("NumberThree", throwIfNotFound: true);
        m_Web_NumberFour = m_Web.FindAction("NumberFour", throwIfNotFound: true);
        m_Web_NumberFive = m_Web.FindAction("NumberFive", throwIfNotFound: true);
        m_Web_NumberSix = m_Web.FindAction("NumberSix", throwIfNotFound: true);
        m_Web_NumberSeven = m_Web.FindAction("NumberSeven", throwIfNotFound: true);
        m_Web_NumberEight = m_Web.FindAction("NumberEight", throwIfNotFound: true);
        m_Web_NumberNine = m_Web.FindAction("NumberNine", throwIfNotFound: true);
        m_Web_NumberZero = m_Web.FindAction("NumberZero", throwIfNotFound: true);
        m_Web_Submit = m_Web.FindAction("Submit", throwIfNotFound: true);
        m_Web_Clear = m_Web.FindAction("Clear", throwIfNotFound: true);
        m_Web_Delete = m_Web.FindAction("Delete", throwIfNotFound: true);
        m_Web_NegativeSign = m_Web.FindAction("NegativeSign", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Web
    private readonly InputActionMap m_Web;
    private IWebActions m_WebActionsCallbackInterface;
    private readonly InputAction m_Web_NumberOne;
    private readonly InputAction m_Web_NumberTwo;
    private readonly InputAction m_Web_NumberThree;
    private readonly InputAction m_Web_NumberFour;
    private readonly InputAction m_Web_NumberFive;
    private readonly InputAction m_Web_NumberSix;
    private readonly InputAction m_Web_NumberSeven;
    private readonly InputAction m_Web_NumberEight;
    private readonly InputAction m_Web_NumberNine;
    private readonly InputAction m_Web_NumberZero;
    private readonly InputAction m_Web_Submit;
    private readonly InputAction m_Web_Clear;
    private readonly InputAction m_Web_Delete;
    private readonly InputAction m_Web_NegativeSign;
    public struct WebActions
    {
        private @InputAsset m_Wrapper;
        public WebActions(@InputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @NumberOne => m_Wrapper.m_Web_NumberOne;
        public InputAction @NumberTwo => m_Wrapper.m_Web_NumberTwo;
        public InputAction @NumberThree => m_Wrapper.m_Web_NumberThree;
        public InputAction @NumberFour => m_Wrapper.m_Web_NumberFour;
        public InputAction @NumberFive => m_Wrapper.m_Web_NumberFive;
        public InputAction @NumberSix => m_Wrapper.m_Web_NumberSix;
        public InputAction @NumberSeven => m_Wrapper.m_Web_NumberSeven;
        public InputAction @NumberEight => m_Wrapper.m_Web_NumberEight;
        public InputAction @NumberNine => m_Wrapper.m_Web_NumberNine;
        public InputAction @NumberZero => m_Wrapper.m_Web_NumberZero;
        public InputAction @Submit => m_Wrapper.m_Web_Submit;
        public InputAction @Clear => m_Wrapper.m_Web_Clear;
        public InputAction @Delete => m_Wrapper.m_Web_Delete;
        public InputAction @NegativeSign => m_Wrapper.m_Web_NegativeSign;
        public InputActionMap Get() { return m_Wrapper.m_Web; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WebActions set) { return set.Get(); }
        public void SetCallbacks(IWebActions instance)
        {
            if (m_Wrapper.m_WebActionsCallbackInterface != null)
            {
                @NumberOne.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberOne;
                @NumberOne.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberOne;
                @NumberOne.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberOne;
                @NumberTwo.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberTwo;
                @NumberTwo.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberTwo;
                @NumberTwo.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberTwo;
                @NumberThree.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberThree;
                @NumberThree.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberThree;
                @NumberThree.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberThree;
                @NumberFour.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberFour;
                @NumberFour.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberFour;
                @NumberFour.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberFour;
                @NumberFive.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberFive;
                @NumberFive.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberFive;
                @NumberFive.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberFive;
                @NumberSix.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberSix;
                @NumberSix.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberSix;
                @NumberSix.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberSix;
                @NumberSeven.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberSeven;
                @NumberSeven.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberSeven;
                @NumberSeven.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberSeven;
                @NumberEight.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberEight;
                @NumberEight.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberEight;
                @NumberEight.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberEight;
                @NumberNine.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberNine;
                @NumberNine.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberNine;
                @NumberNine.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberNine;
                @NumberZero.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberZero;
                @NumberZero.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberZero;
                @NumberZero.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNumberZero;
                @Submit.started -= m_Wrapper.m_WebActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnSubmit;
                @Clear.started -= m_Wrapper.m_WebActionsCallbackInterface.OnClear;
                @Clear.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnClear;
                @Clear.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnClear;
                @Delete.started -= m_Wrapper.m_WebActionsCallbackInterface.OnDelete;
                @Delete.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnDelete;
                @Delete.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnDelete;
                @NegativeSign.started -= m_Wrapper.m_WebActionsCallbackInterface.OnNegativeSign;
                @NegativeSign.performed -= m_Wrapper.m_WebActionsCallbackInterface.OnNegativeSign;
                @NegativeSign.canceled -= m_Wrapper.m_WebActionsCallbackInterface.OnNegativeSign;
            }
            m_Wrapper.m_WebActionsCallbackInterface = instance;
            if (instance != null)
            {
                @NumberOne.started += instance.OnNumberOne;
                @NumberOne.performed += instance.OnNumberOne;
                @NumberOne.canceled += instance.OnNumberOne;
                @NumberTwo.started += instance.OnNumberTwo;
                @NumberTwo.performed += instance.OnNumberTwo;
                @NumberTwo.canceled += instance.OnNumberTwo;
                @NumberThree.started += instance.OnNumberThree;
                @NumberThree.performed += instance.OnNumberThree;
                @NumberThree.canceled += instance.OnNumberThree;
                @NumberFour.started += instance.OnNumberFour;
                @NumberFour.performed += instance.OnNumberFour;
                @NumberFour.canceled += instance.OnNumberFour;
                @NumberFive.started += instance.OnNumberFive;
                @NumberFive.performed += instance.OnNumberFive;
                @NumberFive.canceled += instance.OnNumberFive;
                @NumberSix.started += instance.OnNumberSix;
                @NumberSix.performed += instance.OnNumberSix;
                @NumberSix.canceled += instance.OnNumberSix;
                @NumberSeven.started += instance.OnNumberSeven;
                @NumberSeven.performed += instance.OnNumberSeven;
                @NumberSeven.canceled += instance.OnNumberSeven;
                @NumberEight.started += instance.OnNumberEight;
                @NumberEight.performed += instance.OnNumberEight;
                @NumberEight.canceled += instance.OnNumberEight;
                @NumberNine.started += instance.OnNumberNine;
                @NumberNine.performed += instance.OnNumberNine;
                @NumberNine.canceled += instance.OnNumberNine;
                @NumberZero.started += instance.OnNumberZero;
                @NumberZero.performed += instance.OnNumberZero;
                @NumberZero.canceled += instance.OnNumberZero;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Clear.started += instance.OnClear;
                @Clear.performed += instance.OnClear;
                @Clear.canceled += instance.OnClear;
                @Delete.started += instance.OnDelete;
                @Delete.performed += instance.OnDelete;
                @Delete.canceled += instance.OnDelete;
                @NegativeSign.started += instance.OnNegativeSign;
                @NegativeSign.performed += instance.OnNegativeSign;
                @NegativeSign.canceled += instance.OnNegativeSign;
            }
        }
    }
    public WebActions @Web => new WebActions(this);
    public interface IWebActions
    {
        void OnNumberOne(InputAction.CallbackContext context);
        void OnNumberTwo(InputAction.CallbackContext context);
        void OnNumberThree(InputAction.CallbackContext context);
        void OnNumberFour(InputAction.CallbackContext context);
        void OnNumberFive(InputAction.CallbackContext context);
        void OnNumberSix(InputAction.CallbackContext context);
        void OnNumberSeven(InputAction.CallbackContext context);
        void OnNumberEight(InputAction.CallbackContext context);
        void OnNumberNine(InputAction.CallbackContext context);
        void OnNumberZero(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnClear(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
        void OnNegativeSign(InputAction.CallbackContext context);
    }
}
